import { randomUUID } from "crypto";
import { mkdir, readFile, rm, writeFile } from "fs/promises";
import path from "path";
import { env } from "../config/env";
import type { StorageProvider } from "./provider";

const baseDir = path.resolve(process.cwd(), env.LOCAL_STORAGE_DIR);

async function ensureBaseDir() {
  await mkdir(baseDir, { recursive: true });
}

function resolveKeyPath(storageKey: string) {
  // storageKey is always server-generated by save() below, never user input —
  // this resolve+prefix check is defense in depth, not the primary guard.
  const resolved = path.resolve(baseDir, storageKey);
  if (!resolved.startsWith(baseDir)) {
    throw new Error("Invalid storage key");
  }
  return resolved;
}

export const localStorageProvider: StorageProvider = {
  async save(buffer, extension) {
    await ensureBaseDir();
    const storageKey = `${randomUUID()}${extension}`;
    await writeFile(resolveKeyPath(storageKey), buffer);
    return storageKey;
  },

  async read(storageKey) {
    return readFile(resolveKeyPath(storageKey));
  },

  async delete(storageKey) {
    await rm(resolveKeyPath(storageKey), { force: true });
  },
};
